Different light sources
codefloww/Ray-Tracer pull request #25
Opened 2023-05-07 13:20 UTC by SmalRat

Added different light sources, fixed many bugs in test intersections logic, added gamma correction (which is off now), and optimized work with SDL2 buffers (and overall). Some code is commented - can be used in the future when optimized or I didn't understand its purpose so was afraid to remove it.

2023-05-08 13:49 UTC, codefloww requested changes

2023-05-08 13:49 UTC, codefloww commented on inc/app/image.hpp
> +    Uint32 *m_pixels = nullptr;
Rename variable to match naming convention for pixels_m

2023-05-08 13:49 UTC, codefloww commented on inc/app/image.hpp
> +    int m_pitch = 0;
Rename to match naming convention to pitch_m

2023-05-08 13:49 UTC, codefloww commented on inc/app/scene.hpp
>  #include <memory>
Move all headers that are not immediately necessary to the `scene.cpp`

2023-05-08 13:49 UTC, codefloww commented on inc/app/scene.hpp
> +    std::vector<std::shared_ptr<LightSource>> light_list_m;
Replace std::shared_ptr with raw pointer

2023-05-08 13:49 UTC, codefloww commented on inc/app/scene.hpp
> +    computeColor(const Ray &camera_ray, const Object* const current_object, const glm::vec3 &int_point,
The second const is redundant as it's declaration, and we already have const-qualified argument. Consider removing it.

2023-05-08 13:49 UTC, codefloww commented on inc/app/scene.hpp
> +    inline static void accumulateColors(glm::vec3 diffuse_component,
Consider rewriting signature of function to be just void function
P.S As can be seen in `scene.cpp` it might be a better solution to move out code from this function just to the place of its usage

2023-05-08 13:49 UTC, codefloww commented on inc/lights/directional_light.hpp
> +    static constexpr float M_ATTENUATION_QUADRATIC_MEMBER = 0.0f;
Consider using shorter variable names which satisfy naming convention in form of kPascalCase

2023-05-08 13:49 UTC, codefloww commented on inc/lights/directional_light.hpp
> +    [[nodiscard]] inline double getAttenuation(const glm::vec3 &int_point) const override;
Consider making return type a float

2023-05-08 13:49 UTC, codefloww commented on inc/app/scene.hpp
> +    inline static void accumulateColors(glm::vec3 diffuse_component,
Additionally, why `ambient_component` is not passed by reference?

2023-05-08 13:49 UTC, codefloww commented on inc/lights/directional_light.hpp
> +                             std::pair<glm::vec3, float> &specular_component,
Overall, it seems unnecessary to make `specular_component` a pair, as it later will anyway be calculated in the `computeColor` scope

2023-05-08 13:49 UTC, codefloww commented on inc/app/image.hpp
> +extern const float GAMMA;
Don't understand why you would want to make it a global variable, as you would use it in `image.cpp`, where you already created constexpr of this variable

2023-05-08 13:49 UTC, codefloww commented on inc/lights/light_source.hpp
> +    float m_ambient_intensity;
Rename to satisfy convention, also consider setting a default value for these variables

2023-05-08 13:49 UTC, codefloww commented on inc/lights/light_source.hpp
> +                                     glm::vec3 &ambient_component) const = 0;
Same as in `directional_light.hpp`

2023-05-08 13:49 UTC, codefloww commented on inc/lights/point_light.hpp
> +    [[nodiscard]] inline double getAttenuation(const glm::vec3 &int_point) const override;
Consider making it a float function

2023-05-08 13:49 UTC, codefloww commented on inc/lights/spotlight.hpp
General suggestions as for the previous light sources

2023-05-08 13:49 UTC, codefloww commented on inc/objects/sphere.hpp
Rollback to use general transformations

2023-05-08 13:49 UTC, codefloww commented on src/app/image.cpp
> +#include <iostream>
Remove unused header

2023-05-08 13:49 UTC, codefloww commented on src/app/image.cpp
> +    m_pitch = width_m * uint32_size;
No need to create it as separate variable
```suggestion
    m_pitch = width_m * static_cast<int>(sizeof(Uint32));
```

2023-05-08 13:49 UTC, codefloww commented on src/app/scene.cpp
> +                                diffuse_color, specular_color, ambient_color, shininess);
Restructure to use code from accumulateColors right in this scope

2023-05-08 13:49 UTC, codefloww commented on src/app/scene.cpp
> +}
Feels unnecessary, better to write it entirely in `internalRender`

2023-05-08 13:49 UTC, codefloww commented on src/app/scene.cpp
> +    closest_loc_normal = glm::normalize(closest_loc_normal);
`closest_loc_normal` is normalized anyway, as it's a copy of `loc_normal` which is normalized previously in `testIntersections`. Consider removing normalization in one of two places

2023-05-08 13:49 UTC, codefloww commented on src/app/scene.cpp
> +tbb::enumerable_thread_specific<float> local_max_color;
Because of the dimming/flickering issues, consider just capping color to 1, and not calculating max_color

2023-05-08 13:49 UTC, codefloww commented on src/app/scene.cpp
> +    float shininess = current_object->getMaterial().getShininess();
Can be later replaces when needed with just current_object->material_m.getShininess()

2023-05-08 13:49 UTC, codefloww commented on src/lights/directional_light.cpp
General recommendation as for all previous ligth sources

2023-05-08 13:49 UTC, codefloww commented on src/lights/directional_light.cpp
> +    m_ambient_intensity = 0.005f;
Such small coefficient seems odd, as it will have no impact at all, or just +1 to 255-color. Also, it generally can be moved out to all light-sources and scene, as by the nature of ambient light, it relates to all scene with the same power. So consider using ambient model in some way similar to used before

2023-05-08 13:49 UTC, codefloww commented on src/lights/directional_light.cpp
> +    m_ambient_intensity = 0.005f;
Rename up to the convention

2023-05-08 13:49 UTC, codefloww commented on src/lights/point_light.cpp
As for the previous light_sources

2023-05-08 13:49 UTC, codefloww commented on src/lights/spotlight.cpp
As for the previous light_sources

2023-05-08 13:49 UTC, codefloww commented on src/objects/sphere.cpp
> +        loc_normal = glm::normalize(int_point - m_center);
By the previous change for `t1 alwaly bigger than t2` this if looks redundant.

2023-05-08 17:41 UTC, SmalRat commented on inc/app/image.hpp
> +    Uint32 *m_pixels = nullptr;
Done

2023-05-08 17:41 UTC, SmalRat commented on inc/app/image.hpp
> +    int m_pitch = 0;
Done

2023-05-08 17:41 UTC, SmalRat commented on inc/app/scene.hpp
>  #include <memory>
Done

2023-05-08 17:42 UTC, SmalRat commented on inc/app/scene.hpp
> +    std::vector<std::shared_ptr<LightSource>> light_list_m;
Done

2023-05-08 17:42 UTC, SmalRat commented on inc/app/scene.hpp
> +    computeColor(const Ray &camera_ray, const Object* const current_object, const glm::vec3 &int_point,
Done

2023-05-08 17:45 UTC, SmalRat commented on inc/app/scene.hpp
> +    inline static void accumulateColors(glm::vec3 diffuse_component,
accumulateColors() was created with the purpose to be extended in the future, when it would be probably useful, for example for reflections. Currently, it's overkill.
Inlined the code.

2023-05-08 17:45 UTC, SmalRat commented on inc/lights/directional_light.hpp
> +    static constexpr float M_ATTENUATION_QUADRATIC_MEMBER = 0.0f;
Done

2023-05-08 17:45 UTC, SmalRat commented on inc/lights/directional_light.hpp
> +    [[nodiscard]] inline double getAttenuation(const glm::vec3 &int_point) const override;
Done (everywhere)

2023-05-08 17:46 UTC, SmalRat commented on inc/lights/directional_light.hpp
> +                             std::pair<glm::vec3, float> &specular_component,
Changed the logic and corrected this.

2023-05-08 17:47 UTC, SmalRat commented on inc/app/image.hpp
> +extern const float GAMMA;
Wasn't sure, if I would need to use them in other files. Currently deleted.

2023-05-08 17:47 UTC, SmalRat commented on inc/lights/light_source.hpp
> +                                     glm::vec3 &ambient_component) const = 0;
Done

2023-05-08 17:48 UTC, SmalRat commented on inc/lights/point_light.hpp
> +    [[nodiscard]] inline double getAttenuation(const glm::vec3 &int_point) const override;
Done

2023-05-08 17:50 UTC, SmalRat commented on inc/objects/sphere.hpp
Rolled back. However, it is worth remembering, how much it decreases fps...

2023-05-08 17:50 UTC, SmalRat commented on inc/lights/spotlight.hpp
Done

2023-05-08 17:50 UTC, SmalRat commented on inc/lights/light_source.hpp
> +    float m_ambient_intensity;
Done

2023-05-08 17:51 UTC, SmalRat commented on src/app/image.cpp
> +#include <iostream>
Done

2023-05-08 17:52 UTC, SmalRat commented on src/app/image.cpp
> +    m_pitch = width_m * uint32_size;
Fixed

2023-05-08 17:52 UTC, SmalRat commented on src/app/scene.cpp
> +                                diffuse_color, specular_color, ambient_color, shininess);
Done

2023-05-08 17:52 UTC, SmalRat commented on src/app/scene.cpp
> +}
It had a purpose, but for now, it's overkill. Deleted.

2023-05-08 17:58 UTC, SmalRat commented on src/app/scene.cpp
> +    closest_loc_normal = glm::normalize(closest_loc_normal);
Normals from testIntersections were not guaranteed to be normalized by our conventions, and as callee is responsible for that, this line is needed. However, it is indeed reasonable to delete it here and to condition for the future that testIntersections always returns normalized normals.

2023-05-08 17:59 UTC, SmalRat commented on src/app/scene.cpp
> +    float shininess = current_object->getMaterial().getShininess();
Done

2023-05-08 17:59 UTC, SmalRat commented on src/lights/directional_light.cpp
Done

2023-05-08 17:59 UTC, SmalRat commented on src/lights/directional_light.cpp
> +    m_ambient_intensity = 0.005f;
Done

2023-05-08 17:59 UTC, SmalRat commented on src/lights/spotlight.cpp
Done

2023-05-08 18:05 UTC, SmalRat commented on src/objects/sphere.cpp
> +        loc_normal = glm::normalize(int_point - m_center);
No longer relevant, as rolled back to transformations.
Actually, this "if" wasn't redundant. It was needed to determine, whether we should take smaller t2 as the nearest point of intersection, or it is in the opposite to the ray's direction, so we are inside the sphere and should take t1. And corresponding normal direction.

2023-05-08 18:05 UTC, SmalRat commented on src/lights/point_light.cpp
Done

2023-05-08 18:05 UTC, SmalRat commented on src/app/scene.cpp
> +tbb::enumerable_thread_specific<float> local_max_color;
To be tested.

2023-05-10 17:16 UTC, codefloww approved these changes

2023-05-11 15:01 UTC, merged